modules/routes/user/routes.py
import datetime
from typing import List, Dict, Union

from models import Plan
from modules.routes.user.custom_fields import EmployeeInfoTextAreaField, ISimpleEmployee
from modules.routes.utils.classes.class_utils import ManipulationType, OperationType, SupportedTimeFormats
from modules.routes.utils.functions.function_utils import is_duplicate_plan, short_error, short_success, \
    find_all_employees, custom_strftime, is_expired_plan
from server import mysql
from datetime import datetime
from flask import Blueprint, render_template, request, jsonify, redirect, flash, session, url_for
from modules.routes.user.forms import create_plan_form, get_plan_form, Forminator
from modules.decorators.utils import login_required
from modules.middleware.logic import execute_orders

user_bp = Blueprint('user_bp', __name__,
                    template_folder='templates', static_folder='static')


@user_bp.route('/overview/', methods=['GET'])
@login_required(session)
def overview(ctx=None):
    return render_template('overview/dash_overview_partial.html')


@user_bp.route('/profile/', methods=['GET', 'POST'])
@login_required(session)
def profile(ctx=None):
    conn = mysql.connect()
    cursor = conn.cursor()
    query = 'SELECT description FROM manager WHERE email = %s'
    cursor.execute(query, (session['manager_email']))
    description = cursor.fetchall()[0][0]

    conn.close()

    if description is None or description.strip() == '':
        description = "None Provided"

    return render_template('profile/profile.html', description=description)


@user_bp.route('/logout/', methods=['GET'])
@login_required(session)
def logout(ctx=None):
    session.clear()
    flash("Logout Successful", category='success')
    return redirect(url_for('common_bp.login'))


@user_bp.route('/create_plan/', methods=['GET', 'POST'])
@login_required(session)
def create_plan():
    form = create_plan_form(session)

    if request.method == 'GET':
        return render_template('plans/create_plan/create_plan_partial.html', form=form,
                               current_date=custom_strftime(SupportedTimeFormats.FMT_SIDE_UI, datetime.now()))
    else:
        if form.validate_on_submit():
            conn = mysql.connect()
            cursor = conn.cursor()
            return create_plan_execution(conn, cursor, Forminator(form))
        else:
            return short_error(form)


def create_plan_execution(conn, cursor, fmr: Forminator):
    if is_duplicate_plan(mysql, fmr.plan_name):
        return short_error(err_list=['This plan already exists. Go to Manage Plan to learn more.'])

    if fmr.disbursement_type == fmr.raw_form.DISB_ALL:
        employees = find_all_employees(cursor, session['manager_dept'])

        if employees is None:
            return short_error(err_list=['No employees were found in the department'])
        fmr.employees_list = employees['data']

    p = Plan(cursor, conn=conn)
    p.insert(fmr)
    conn.close()

    execute_orders()
    return short_success(ManipulationType.CREATED)


@user_bp.route('/manage_plan/', methods=['GET', 'POST'])
@login_required(session)
def manage_plan():

    form = get_plan_form(session)

    if request.method == 'GET':
        return render_template('plans/manage_plan/manage_plan_partial.html', form=form,
                               current_date=custom_strftime(SupportedTimeFormats.FMT_SIDE_UI, datetime.now()))
    else:
        plan_fmt = session.get('MANAGE_FORM')

        if plan_fmt is None:
            return jsonify(response="A search query must be made to update it")

        form = get_plan_form(session)

        if form.validate_on_submit():
            conn = mysql.connect()
            cursor = conn.cursor()
            return manipulate_plan(conn, cursor, Forminator(form), plan_fmt)
        else:
            return short_error(form=form)


def manipulate_plan(conn, cursor, fmr, plan_fmt):

    if plan_fmt['plan_name'] != fmr.plan_name:
        if is_duplicate_plan(mysql, fmr.plan_name):
            return short_error(err_list=['This plan is already exists'])

    if plan_fmt['is_active']:
        return short_error(err_list=['This plan is currently active'])

    if is_expired_plan(mysql, fmr.plan_name):
        return short_error(err_list=['This plan is expired and is read-only.'])

    p = Plan(cursor, conn=conn)
    p.update(fmr, plan_fmt['id'])

    q_del = """DELETE FROM employee_plan WHERE ep_employee_FK = %s AND ep_plan_FK = %s"""
    q_ins = """INSERT INTO employee_plan(ep_employee_FK, ep_plan_FK) VALUES (%s, %s)"""
    uq = get_unique_employees(plan_fmt['employees_list'], fmr.employees_list)

    if uq['operation'] == OperationType.DELETE_EMPLOYEE:
        [cursor.execute(q_del, (record['id'], plan_fmt['id'])) for record in uq['diff_list']]
    else:
        [cursor.execute(q_ins, (record['id'], plan_fmt['id'])) for record in uq['diff_list']]

    conn.commit()
    conn.close()
    return short_success(ManipulationType.UPDATED)


def get_unique_employees(old_list, new_list: List[EmployeeInfoTextAreaField]) -> Dict[str, Union[List[dict],
                                                                                                 OperationType]]:
    """
    We get the old list of employees as a list of dictionaries and a new list of employees as
    a list of EmployeeInfoTextAreaField's from the form. The issue is a bit tricky because
    it becomes hard to tell when a user added or removed employees. It's very naive to rely on the
    length of the two lists.

    For example, let's say the manager removed the following employees

    x = [{"Manu": 1}, {"Sam": 2}, {"Will": 3}, {"Yijian": 4}]

    and added new ones:

    y = [{"Jack": 1}, {"Jill": 2}, {"Bill": 3}, {"Dill": 4}]

    How would you keep track of what employees were to be removed?

    Another example, If the manager adds to new employees

    y = [{"Manu": 1}, {"Sam": 2}, {"Will": 3}, {"Yijian": 4}, {"Aang": 5}, {"Appa": 10}]

    How would you figure out which ones were added? What if they were removed?

    y = [{"Manu": 1}, {"Sam": 2}, {"Will": 3}]

    Enter sets. https://docs.python.org/2/library/sets.html#set-objects
    We can convert each dictionary and group them as a set. Initially, we
    take the difference between the new and old set. If the result is an empty set, it could mean that new employees
    were added. In this case, we check the length of the new list and take the systematic difference of both sets.
    If the result was not an empty set, it means that employees were removed or changed

    *Note. The new list comes in as a list of EmployeeInfoTextAreaFields. If it's empty, it defaults to ['']. In this
    case, we just change that to an empty set:  set()

    Depending on what kind of set operation we did, we can return the type of the operation as an OperationType enum
    class.

    :param old_list: The previous list of employees
    :param new_list: The new list of employees
    :return: A dictionary containing the list of employees and the operation(add or delete)
    """

    add_employees = False

    set_list1 = set(tuple(sorted(d.items())) for d in old_list)
    set_list2 = set() if new_list[0] == '' else set(tuple(sorted(d.items())) for d in new_list)

    diff = set_list1 - set_list2

    if len(diff) == 0:
        if len(new_list) > len(old_list):
            diff = set_list1 ^ set_list2
            add_employees = True

    diff_list = []
    for tup in diff:
        diff_list.append(dict((x, y) for x, y in tup))

    return {
        "diff_list": diff_list,
        "operation": OperationType.ADD_EMPLOYEE if add_employees else OperationType.DELETE_EMPLOYEE
    }

modules/routes/user/templates/alert_partial.html
<div class="alert {% if status %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show mb-0"
     role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    {% if status %}
        <i class="fa fa-info mx-2"></i>
        <strong>Your plan has been {{ manip_type }}</strong>
    {% else %}
        {% if form is defined %}
            {% for field, errors in form.errors.items() %}
                {% for error in form.errors[field] %}
                    <i class="fa fa-times mx-2"></i>
                    <strong>{{ error }}</strong>
                    <br>
                {% endfor %}
            {% endfor %}
        {% else %} {# List of custom errors non-form related #}
            {% if err_list is defined %}
                {% for error in err_list %}
                    <i class="fa fa-times mx-2"></i>
                    <strong>{{ error }}</strong>
                {% endfor %}
            {% endif %}
        {% endif %}
    {% endif %}
</div>

modules/routes/user/templates/dash_base.html
<!DOCTYPE html>
<html lang="en" class="no-js h-100">
<head>
    {% block base_head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Marqeta Hackathon Project - MEET - Dashboard">
        <meta name="author" content="Manu Puduvalli | Samuel Yuen | William Vega | Yi-jian Ma Ma">
        <title>{% block base_title %}{% endblock %} · {{ session['company_name'] }} Dashboard</title>

        {% include 'static_links.html' %}

        {% assets "base_css" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}">
        {% endassets %}

        {% assets "base_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% assets "dash_css" %}
            <link rel="stylesheet" id="main-stylesheet" href="{{ ASSET_URL }}">
        {% endassets %}

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="/static/libs/chartjs/Chart.min.js"></script>
        <script src="/static/libs/datatables/dataTables.min.js"></script>
        <script src="/static/libs/datatables/dataTables.buttons.min.js"></script>
        <script src="/static/libs/datatables/pdfmake.min.js"></script>
        <script src="/static/libs/datatables/buttons.print.min.js"></script>
        <script src="/static/libs/datatables/jszip.min.js"></script>
        <script src="/static/libs/datatables/vfs_fonts.js"></script>
        <script src="/static/libs/datatables/vfs_fonts.js"></script>
        <script src="/static/libs/datatables/buttons.html5.min.js"></script>
        <script src="{{ url_for('user_bp.static', filename='js/darkreader.min.js') }}"></script>
    {% endblock %}
</head>
<body class="h-100">
<div class="container-fluid">
    <div class="row">
        <!-- Main Sidebar -->
        <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
            <div class="main-navbar">
                <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
                    <a class="navbar-brand w-100 mr-0" href="{{ url_for('user_bp.overview') }}"
                       style="line-height: 45px;">
                        <div class="d-table m-auto">
                            <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 45px;"
                                 src="/static/images/logos/Generic%20Company%20Logo.png"
                                 alt="{{ session['company_name'] }}">
                            <span id="companyName"
                                  class="d-md-inline ml-1 font-weight-bold primary-md">{{ session['company_name'] }}</span>
                        </div>
                    </a>
                    <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                        <i class="material-icons">&#xE5C4;</i>
                    </a>
                </nav>
            </div>
            <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
                <div class="input-group input-group-seamless ml-3">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fas fa-search"></i>
                        </div>
                    </div>
                    <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                           aria-label="Search"></div>
            </form>
            <div class="nav-wrapper">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link {%- if request.path == url_for('user_bp.overview') %} active {%- endif %}"
                           href="{{ url_for('user_bp.overview') }}">
                            <i class="material-icons">edit</i>
                            <span>Company Overview</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {%- if request.path == url_for('user_bp.create_plan') %} active {%- endif %}"
                           href="{{ url_for('user_bp.create_plan') }}">
                            <i class="material-icons">vertical_split</i>
                            <span>Create Plan</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {%- if request.path == url_for('user_bp.manage_plan') %} active {%- endif %}"
                           href="{{ url_for('user_bp.manage_plan') }}">
                            <i class="material-icons">note_add</i>
                            <span>Manage Plans</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{%- if request.path == url_for('user_bp.profile') %} active {%- endif %}"
                           href="{{ url_for('user_bp.profile') }}">
                            <i class="material-icons">person</i>
                            <span>User Profile</span>
                        </a>
                    </li>
                </ul>
            </div>
        </aside>
        <!-- End Main Sidebar -->
        <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
            <div class="main-navbar sticky-top bg-white">
                <!-- Main Navbar -->
                <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
                    <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
                        <div class="input-group input-group-seamless ml-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-search"></i>
                                </div>
                            </div>
                            <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                                   aria-label="Search"></div>
                    </form>
                    <ul class="navbar-nav border-left flex-row ">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                {% if session['manager_gender'] == 'MALE' %}
                                    <img class="user-avatar rounded-circle mr-2"
                                         src="{{ url_for('user_bp.static', filename='images/avatars/1.jpg') }}"
                                         alt="Picture of {{ session['manager_fname'] }} {{ session['manager_lname'] }}">
                                {% else %}
                                    <img class="user-avatar rounded-circle mr-2"
                                         src="{{ url_for('user_bp.static', filename='images/avatars/0.jpg') }}"
                                         alt="Picture of {{ session['manager_fname'] }} {{ session['manager_lname'] }}">
                                {% endif %}
                                <span class="d-none d-md-inline-block">{{ session['manager_fname'] }} {{ session['manager_lname'] }}</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-small">
                                <a class="dropdown-item" href="{{ url_for('user_bp.profile') }}">
                                    <i class="material-icons">&#xE7FD;</i> Profile</a>
                                <a class="dropdown-item" href="{{ url_for('user_bp.create_plan') }}">
                                    <i class="material-icons">note_add</i> Add New Plan</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="{{ url_for('user_bp.logout') }}">
                                    <i class="material-icons text-danger">&#xE879;</i> Logout </a>
                            </div>
                        </li>
                    </ul>
                    <nav class="nav">
                        <a href="#"
                           class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left"
                           data-toggle="collapse" data-target=".header-navbar" aria-expanded="false"
                           aria-controls="header-navbar">
                            <i class="material-icons">&#xE5D2;</i>
                        </a>
                    </nav>
                </nav>
            </div>

            {% block dashboard_main %}
            {% endblock dashboard_main %}

            <footer class="main-footer d-flex p-2 px-3 bg-white border-top">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="https://www.github.com/manu-p-1/meet">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="https://www.marqeta.com">Marqeta Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="https://www.marqeta.com/docs/core-api/introduction">Marqeta
                            Core API</a>
                    </li>
                    <li class="nav-item">
                        <div class="nav-link" id="darkModeSelector">
                            <span id="darkModeSelectorText">Enable Dark Mode</span>
                            <i class="material-icons mr-1 mb-0">nights_stay</i>
                        </div>
                    </li>
                </ul>
                <span class="copyright ml-auto my-auto mr-2">Copyright © 2020
              <a href="#" rel="nofollow">MEET</a>
            </span>
            </footer>
        </main>
    </div>
    {% include "modals_partial.html" %}
</div>

{% assets "dash_js" %}
    <script src="{{ ASSET_URL }}"></script>
{% endassets %}


</body>
</html>

modules/routes/user/templates/modals_partial.html
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <img class="d-inline-block mr-2" src="/static/images/logos/Generic%20Company%20Logo.png"
                     width="35" alt="{{ session['company_name'] }} Logo">

                <h5 class="modal-title d-inline-block" id="confirmModalLabel">Are you sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-modal-cancel" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary btn-modal-proceed" data-dismiss="modal">Continue</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <img class="d-inline-block mr-2" src="/static/images/logos/Generic%20Company%20Logo.png"
                     width="35" alt="{{ session['company_name'] }} Logo">

                <h5 class="modal-title d-inline-block" id="errorModalLabel">An Error Occurred</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btn-modal-proceed" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>